spring:
  application:
    name: image-recognition
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:80899
server:
  port: 80899
